<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>c3b39c9c-3ed6-4f10-b6f0-5e3b8e3ae5fe</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Confluent.Kafka" Version="2.6.3" />
        <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\PvpAnalytics.Infrastructure\PvpAnalytics.Infrastructure.csproj" />
      <ProjectReference Include="..\PvpAnalytics.Application\PvpAnalytics.Application.csproj" />
      <ProjectReference Include="..\..\..\Shared\PvpAnalytics.Shared\PvpAnalytics.Shared.csproj" />
    </ItemGroup>

</Project>
